# LOGGING
logging:
  level:
    org.springframework.web: DEBUG

  # APPLICATION
spring:
  application:
    name: turkcell-customer-logger-poc

  data:
    elasticsearch:
      cluster-nodes: ${ELASTICSEARCH_URL}
      cluster-name: ${ELASTICSEARCH_CLUSTER}



kafka-client-id: customerupdaterclient
kafka-bootstrap-servers: ${KAFKA_URL}
kafka-consumer-key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
kafka-consumer-value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
auto_commit_interval_ms_config: 1000
session_timeout_ms_config: 30000

kafka-order-topic: customerupdater
kafka-order-group-id: kafka-collector

server:
  port: 8064
  servlet:
    context-path: /customer-logger
